### ISSUE TITLE
Simple forms Question

### ISSUE THREAD

**Issue by Greenjam94** [Greenjam94/tc359_rails_final#3]
Hello again @chrisvfritz,

I'm trying to use simple forms for all forms. I got it working for adding new contacts but it's breaking for creating users. I hope you have an idea. I think I need to set request action to "create" instead of "new".

Here's a screenshot of the error:
![screen shot 2015-04-19 at 9 31 59 pm](https://cloud.githubusercontent.com/assets/5766832/7222389/901fe03a-e6db-11e4-87d7-7047498a13f5.png)

**Comment by chrisvfritz** [comment]
Try changing line 3 here to:

``` erb
<%= simple_form_for @user do |f| %>
```

The object we're creating the form for (in this case, `@user`) is always passed into the form. And I believe the `:action => '/create'` should be redundant in this case, as simple_form *should* automatically submit to that location unless told otherwise.

Let me know if that works!

**Comment by Greenjam94** [comment]
I tried that first, I get a nil class error and I'm not sure why, sessions_controller has user=User.find... but the new function is empty. I think I need to call the create function instead of new.  which is why I had tried specifying it.

![screen shot 2015-04-21 at 10 32 03 am](https://cloud.githubusercontent.com/assets/5766832/7254530/b29464b0-e811-11e4-8757-71d405b70a26.png)

**Comment by chrisvfritz** [comment]
Ahh, I see. I misread this as the `users/new` file instead of `sessions/new`. This form actually won't be tied to a specific object like @user. Instead, we'll do [something like this](http://stackoverflow.com/questions/5181143/simpleform-without-for-non-model-form). Let me know if that link helps - otherwise I'm happy to guide you further.

**Comment by Greenjam94** [comment]
Yes! That fixed it! I had to debug for the correct params but after a few attempts I can log in! Awesome thank you again!

![screen shot 2015-04-21 at 7 53 22 pm](https://cloud.githubusercontent.com/assets/5766832/7264936/1aabfcb8-e860-11e4-850b-13634f30f8ee.png)
